from fastapi import FastAPI, Request
import subprocess
import requests
import json

app = FastAPI()

# Your server endpoint to send results to
SERVER_UPLOAD_URL = "https://your-server.com/api/upload-scraped/"
SECRET_TOKEN = "MY_SECRET_123"   # change to anything


@app.post("/run-scraper")
async def run_scraper(request: Request):
    # Security check
    token = request.headers.get("X-Secret")
    if token != SECRET_TOKEN:
        return {"error": "unauthorized"}

    print("🔔 Server triggered the scraper...")

    # Run the scraper script locally
    subprocess.run(["python3", "scraper.py"])

    print("✔ Scraper finished. Sending results to server...")

    # Load output file generated by scraper
    with open("output.json", "r") as f:
        data = f.read()

    # Send back to server
    requests.post(
        SERVER_UPLOAD_URL,
        data=data,
        headers={"X-Secret": SECRET_TOKEN}
    )

    print("✔ Data sent back successfully.")
    return {"status": "scraper completed and data sent"}
