# Generated by Django 5.0.7 on 2025-10-28 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("filing_date", models.DateField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("AZ_SOS", "Arizona SOS"),
                            ("COUNTY", "County"),
                            ("OTHER", "Other"),
                        ],
                        default="AZ_SOS",
                        max_length=20,
                    ),
                ),
                ("contacted", models.BooleanField(default=False)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_fake", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DonorEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "entity_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "total_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("is_fake", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="IECommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "committee_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ein", models.CharField(blank=True, max_length=100, null=True)),
                ("is_fake", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("office", models.CharField(blank=True, max_length=200, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("is_fake", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StatementOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("office", models.CharField(blank=True, max_length=255, null=True)),
                ("party", models.CharField(blank=True, max_length=100, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("date_filed", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, help_text="Raw JSON data from the source", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contacted_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("method", models.CharField(default="email", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_contacted", "Not Contacted"),
                            ("contacted", "Contacted"),
                            ("responded", "Responded"),
                            ("pledged", "Pledged"),
                        ],
                        default="not_contacted",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pledged_at", models.DateTimeField(blank=True, null=True)),
                ("is_fake", models.BooleanField(default=False)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_logs",
                        to="transparency.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("date", models.DateField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, null=True)),
                ("is_fake", models.BooleanField(default=False)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transparency.donorentity",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transparency.iecommittee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidate",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="transparency.party",
            ),
        ),
        migrations.CreateModel(
            name="Expenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("date", models.DateField(blank=True, null=True)),
                ("purpose", models.TextField(blank=True, null=True)),
                (
                    "support_oppose",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "candidate_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("raw", models.JSONField(blank=True, null=True)),
                ("is_fake", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transparency.candidate",
                    ),
                ),
                (
                    "ie_committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transparency.iecommittee",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transparency.race",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidate",
            name="race",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="transparency.race",
            ),
        ),
    ]
