# Generated by Django 5.0.7 on 2025-11-05 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BallotMeasure",
            fields=[
                (
                    "ballot_measure_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("sos_identifier", models.CharField(max_length=50, unique=True)),
                ("measure_number", models.CharField(blank=True, max_length=10)),
                ("short_title", models.CharField(max_length=500)),
                ("official_title", models.TextField(blank=True)),
            ],
            options={
                "db_table": "BallotMeasures",
            },
        ),
        migrations.CreateModel(
            name="County",
            fields=[
                ("county_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name_plural": "Counties",
                "db_table": "Counties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Cycle",
            fields=[
                ("cycle_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10)),
                ("begin_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
            options={
                "db_table": "Cycles",
            },
        ),
        migrations.CreateModel(
            name="EntityType",
            fields=[
                (
                    "entity_type_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "EntityTypes",
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                ("category_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Expense Categories",
                "db_table": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                ("office_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("office_type", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "Offices",
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                ("party_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("abbreviation", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "verbose_name_plural": "Parties",
                "db_table": "Parties",
            },
        ),
        migrations.CreateModel(
            name="ReportName",
            fields=[
                (
                    "report_name_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "ReportNames",
            },
        ),
        migrations.CreateModel(
            name="ReportType",
            fields=[
                (
                    "report_type_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ReportTypes",
            },
        ),
        migrations.CreateModel(
            name="TransactionType",
            fields=[
                (
                    "transaction_type_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("income_expense_neutral", models.IntegerField()),
            ],
            options={
                "db_table": "TransactionTypes",
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                ("name_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name_group_id", models.IntegerField(db_index=True)),
                ("last_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("middle_name", models.CharField(blank=True, max_length=255)),
                ("suffix", models.CharField(blank=True, max_length=50)),
                ("address1", models.CharField(blank=True, max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("occupation", models.CharField(blank=True, max_length=255)),
                ("employer", models.CharField(blank=True, max_length=255)),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transparency.county",
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transparency.entitytype",
                    ),
                ),
            ],
            options={
                "db_table": "Names",
            },
        ),
        migrations.CreateModel(
            name="CandidateStatementOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("filing_date", models.DateField()),
                (
                    "contact_status",
                    models.CharField(
                        choices=[
                            ("uncontacted", "Uncontacted"),
                            ("contacted", "Email Sent"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="uncontacted",
                        max_length=20,
                    ),
                ),
                ("contact_date", models.DateField(blank=True, null=True)),
                ("contacted_by", models.CharField(blank=True, max_length=100)),
                ("pledge_received", models.BooleanField(default=False)),
                ("pledge_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="soi_filings",
                        to="transparency.entity",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transparency.office",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Statement of Interest",
                "verbose_name_plural": "Candidate Statements of Interest",
                "db_table": "candidate_soi",
                "ordering": ["-filing_date"],
            },
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "committee_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("is_incumbent", models.BooleanField(default=False)),
                ("sponsor_type", models.CharField(blank=True, max_length=100)),
                ("sponsor_relationship", models.CharField(blank=True, max_length=255)),
                ("benefits_ballot_measure", models.BooleanField(default=False)),
                ("organization_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("physical_address1", models.CharField(blank=True, max_length=255)),
                ("physical_address2", models.CharField(blank=True, max_length=255)),
                ("physical_city", models.CharField(blank=True, max_length=100)),
                ("physical_state", models.CharField(blank=True, max_length=2)),
                ("physical_zip_code", models.CharField(blank=True, max_length=10)),
                (
                    "financial_institution1",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "financial_institution2",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "financial_institution3",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "ballot_measure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="committees",
                        to="transparency.ballotmeasure",
                    ),
                ),
                (
                    "candidate_county",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_committees",
                        to="transparency.county",
                    ),
                ),
                (
                    "election_cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transparency.cycle",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_committees",
                        to="transparency.entity",
                    ),
                ),
                (
                    "chairperson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chaired_committees",
                        to="transparency.entity",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="committee",
                        to="transparency.entity",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsored_committees",
                        to="transparency.entity",
                    ),
                ),
                (
                    "treasurer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treasured_committees",
                        to="transparency.entity",
                    ),
                ),
                (
                    "candidate_office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transparency.office",
                    ),
                ),
                (
                    "candidate_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transparency.party",
                    ),
                ),
            ],
            options={
                "db_table": "Committees",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("report_id", models.IntegerField(primary_key=True, serialize=False)),
                ("report_period_begin", models.DateTimeField()),
                ("report_period_end", models.DateTimeField()),
                ("filing_period_begin", models.DateTimeField()),
                ("filing_period_end", models.DateTimeField()),
                ("filing_datetime", models.DateTimeField()),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="transparency.committee",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transparency.cycle",
                    ),
                ),
                (
                    "original_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendments",
                        to="transparency.report",
                    ),
                ),
                (
                    "report_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transparency.reportname",
                    ),
                ),
                (
                    "report_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transparency.reporttype",
                    ),
                ),
            ],
            options={
                "db_table": "Reports",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("transaction_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_for_benefit", models.BooleanField(blank=True, null=True)),
                ("memo", models.TextField(blank=True)),
                ("account_type", models.CharField(blank=True, max_length=50)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transparency.expensecategory",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="transparency.committee",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="transparency.entity",
                    ),
                ),
                (
                    "modifies_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendments",
                        to="transparency.transaction",
                    ),
                ),
                (
                    "subject_committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_of_ies",
                        to="transparency.committee",
                    ),
                ),
                (
                    "transaction_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transparency.transactiontype",
                    ),
                ),
            ],
            options={
                "db_table": "Transactions",
            },
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["last_name", "first_name"], name="Names_last_na_c97ecf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["name_group_id"], name="Names_name_gr_7a0ab3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidatestatementofinterest",
            unique_together={("candidate_name", "office", "filing_date")},
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["committee", "cycle"], name="Reports_committ_755422_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["filing_datetime"], name="Reports_filing__0bcea4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["committee", "transaction_date"],
                name="Transaction_committ_c9e344_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["entity"], name="Transaction_entity__6d0ff2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type"], name="Transaction_transac_9d9373_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["subject_committee"], name="Transaction_subject_d2b6b2_idx"
            ),
        ),
    ]
