# Generated by Django 5.0.7 on 2025-10-21 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenditure",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenditures",
                to="transparency.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="race",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="transparency.race",
            ),
        ),
        migrations.AlterField(
            model_name="contactlog",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_logs",
                to="transparency.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="expenditure",
            name="ie_committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenditures",
                to="transparency.iecommittee",
            ),
        ),
        migrations.AlterField(
            model_name="expenditure",
            name="race",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenditures",
                to="transparency.race",
            ),
        ),
    ]
