# Generated by Django 5.0.7 on 2025-11-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ballotmeasure",
            options={"ordering": ["-sos_identifier"]},
        ),
        migrations.AlterModelOptions(
            name="committee",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="cycle",
            options={"ordering": ["-begin_date"]},
        ),
        migrations.AlterModelOptions(
            name="entity",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="entitytype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="expensecategory",
            options={"ordering": ["name"], "verbose_name_plural": "Expense Categories"},
        ),
        migrations.AlterModelOptions(
            name="office",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="party",
            options={"ordering": ["name"], "verbose_name_plural": "Parties"},
        ),
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-filing_datetime"]},
        ),
        migrations.AlterModelOptions(
            name="reportname",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="reporttype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-transaction_date", "-amount"]},
        ),
        migrations.AlterModelOptions(
            name="transactiontype",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveIndex(
            model_name="report",
            name="Reports_committ_755422_idx",
        ),
        migrations.RemoveIndex(
            model_name="report",
            name="Reports_filing__0bcea4_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="Transaction_committ_c9e344_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="Transaction_entity__6d0ff2_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="Transaction_subject_d2b6b2_idx",
        ),
        migrations.RenameIndex(
            model_name="entity",
            new_name="idx_entity_name",
            old_name="Names_last_na_c97ecf_idx",
        ),
        migrations.RenameIndex(
            model_name="entity",
            new_name="idx_entity_group",
            old_name="Names_name_gr_7a0ab3_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="idx_txn_type",
            old_name="Transaction_transac_9d9373_idx",
        ),
        migrations.AlterField(
            model_name="ballotmeasure",
            name="measure_number",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="ballotmeasure",
            name="short_title",
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="ballotmeasure",
            name="sos_identifier",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="candidate_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="contact_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="contact_status",
            field=models.CharField(
                choices=[
                    ("uncontacted", "Uncontacted"),
                    ("contacted", "Email Sent"),
                    ("acknowledged", "Acknowledged"),
                ],
                db_index=True,
                default="uncontacted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="email",
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="filing_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="pledge_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="pledge_received",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="committee",
            name="is_incumbent",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="committee",
            name="organization_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="committee",
            name="physical_city",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="committee",
            name="physical_state",
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="committee",
            name="sponsor_type",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="committee",
            name="termination_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="county",
            name="name",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="cycle",
            name="begin_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="cycle",
            name="end_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="cycle",
            name="name",
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="entity",
            name="city",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="entity",
            name="employer",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="entity",
            name="first_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="entity",
            name="last_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="entity",
            name="occupation",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="entity",
            name="state",
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="entity",
            name="zip_code",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="office",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="office",
            name="office_type",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="party",
            name="abbreviation",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="filing_datetime",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="filing_period_end",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_period_begin",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_period_end",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="reportname",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="reporttype",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="reporttype",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="is_for_benefit",
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="transactiontype",
            name="income_expense_neutral",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="transactiontype",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="ballotmeasure",
            index=models.Index(fields=["sos_identifier"], name="idx_ballot_sos_id"),
        ),
        migrations.AddIndex(
            model_name="ballotmeasure",
            index=models.Index(fields=["measure_number"], name="idx_ballot_number"),
        ),
        migrations.AddIndex(
            model_name="ballotmeasure",
            index=models.Index(fields=["short_title"], name="idx_ballot_title"),
        ),
        migrations.AddIndex(
            model_name="candidatestatementofinterest",
            index=models.Index(fields=["candidate_name"], name="idx_soi_name"),
        ),
        migrations.AddIndex(
            model_name="candidatestatementofinterest",
            index=models.Index(
                fields=["office", "-filing_date"], name="idx_soi_office_date"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatestatementofinterest",
            index=models.Index(fields=["-filing_date"], name="idx_soi_date_desc"),
        ),
        migrations.AddIndex(
            model_name="candidatestatementofinterest",
            index=models.Index(fields=["contact_status"], name="idx_soi_status"),
        ),
        migrations.AddIndex(
            model_name="candidatestatementofinterest",
            index=models.Index(
                fields=["contact_status", "-filing_date"], name="idx_soi_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatestatementofinterest",
            index=models.Index(fields=["pledge_received"], name="idx_soi_pledge"),
        ),
        migrations.AddIndex(
            model_name="candidatestatementofinterest",
            index=models.Index(
                fields=["office", "contact_status"], name="idx_soi_office_status"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatestatementofinterest",
            index=models.Index(
                fields=["contact_status", "pledge_received"],
                name="idx_soi_status_pledge",
            ),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(fields=["name"], name="idx_committee_name"),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(fields=["candidate"], name="idx_committee_candidate"),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(
                fields=["candidate_office", "candidate_party"],
                name="idx_committee_office_party",
            ),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(
                fields=["candidate_office", "election_cycle"],
                name="idx_committee_office_cycle",
            ),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(fields=["is_incumbent"], name="idx_committee_incumbent"),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(
                fields=["organization_date"], name="idx_committee_org_date"
            ),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(
                fields=["termination_date"], name="idx_committee_term_date"
            ),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(
                fields=["sponsor", "sponsor_type"], name="idx_committee_sponsor"
            ),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(fields=["ballot_measure"], name="idx_committee_ballot"),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(fields=["election_cycle"], name="idx_committee_cycle"),
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(
                fields=["candidate_party", "candidate_office", "election_cycle"],
                name="idx_committee_race",
            ),
        ),
        migrations.AddIndex(
            model_name="county",
            index=models.Index(fields=["name"], name="idx_county_name"),
        ),
        migrations.AddIndex(
            model_name="cycle",
            index=models.Index(fields=["name"], name="idx_cycle_name"),
        ),
        migrations.AddIndex(
            model_name="cycle",
            index=models.Index(fields=["-begin_date"], name="idx_cycle_begin_desc"),
        ),
        migrations.AddIndex(
            model_name="cycle",
            index=models.Index(
                fields=["begin_date", "end_date"], name="idx_cycle_dates"
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["first_name", "last_name"], name="idx_entity_name_reverse"
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["entity_type", "last_name"], name="idx_entity_type_lastname"
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["city", "state"], name="idx_entity_location"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["state", "city"], name="idx_entity_state_city"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["zip_code"], name="idx_entity_zip"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["employer"], name="idx_entity_employer"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["occupation"], name="idx_entity_occupation"),
        ),
        migrations.AddIndex(
            model_name="entitytype",
            index=models.Index(fields=["name"], name="idx_entitytype_name"),
        ),
        migrations.AddIndex(
            model_name="expensecategory",
            index=models.Index(fields=["name"], name="idx_category_name"),
        ),
        migrations.AddIndex(
            model_name="office",
            index=models.Index(fields=["name"], name="idx_office_name"),
        ),
        migrations.AddIndex(
            model_name="office",
            index=models.Index(fields=["office_type"], name="idx_office_type"),
        ),
        migrations.AddIndex(
            model_name="office",
            index=models.Index(
                fields=["office_type", "name"], name="idx_office_type_name"
            ),
        ),
        migrations.AddIndex(
            model_name="party",
            index=models.Index(fields=["name"], name="idx_party_name"),
        ),
        migrations.AddIndex(
            model_name="party",
            index=models.Index(fields=["abbreviation"], name="idx_party_abbr"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["committee", "-filing_datetime"], name="idx_report_comm_filed"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["cycle"], name="idx_report_cycle"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["-filing_datetime"], name="idx_report_filed_desc"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_period_begin", "report_period_end"],
                name="idx_report_period",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["filing_period_end", "filing_datetime"],
                name="idx_report_deadline",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["committee", "cycle", "report_type"],
                name="idx_report_comm_cycle_type",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["cycle", "report_type"], name="idx_report_cycle_type"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["original_report"], name="idx_report_original"),
        ),
        migrations.AddIndex(
            model_name="reportname",
            index=models.Index(fields=["name"], name="idx_report_name"),
        ),
        migrations.AddIndex(
            model_name="reporttype",
            index=models.Index(fields=["name"], name="idx_report_type_name"),
        ),
        migrations.AddIndex(
            model_name="reporttype",
            index=models.Index(fields=["is_active"], name="idx_report_type_active"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["committee", "-transaction_date"], name="idx_txn_committee_date"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["entity", "-transaction_date"], name="idx_txn_entity_date"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["-transaction_date"], name="idx_txn_date_desc"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["-amount"], name="idx_txn_amount_desc"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["amount"], name="idx_txn_amount_asc"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["subject_committee", "is_for_benefit"], name="idx_txn_ie_target"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["subject_committee", "-amount"], name="idx_txn_ie_amount"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["is_for_benefit", "-amount"], name="idx_txn_ie_benefit"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category", "-amount"], name="idx_txn_category_amount"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["deleted"], name="idx_txn_deleted"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["deleted", "-transaction_date"], name="idx_txn_active_date"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["committee", "transaction_type", "-transaction_date"],
                name="idx_txn_comm_type_date",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "deleted", "-amount"],
                name="idx_txn_type_active_amount",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["subject_committee", "deleted", "-amount"],
                name="idx_txn_ie_active_amount",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_date", "committee"], name="idx_txn_date_committee"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_date", "entity"], name="idx_txn_date_entity"
            ),
        ),
        migrations.AddIndex(
            model_name="transactiontype",
            index=models.Index(fields=["name"], name="idx_txn_type_name"),
        ),
        migrations.AddIndex(
            model_name="transactiontype",
            index=models.Index(
                fields=["income_expense_neutral"], name="idx_txn_type_category"
            ),
        ),
    ]
