# Generated by Django 5.0.7 on 2025-10-29 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="year",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="expenditure",
            name="year",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="committee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="transparency.iecommittee",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="transparency.donorentity",
            ),
        ),
        migrations.AlterField(
            model_name="expenditure",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenditures",
                to="transparency.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="expenditure",
            name="ie_committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenditures",
                to="transparency.iecommittee",
            ),
        ),
        migrations.AlterField(
            model_name="expenditure",
            name="race",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenditures",
                to="transparency.race",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
