# Generated by Django 5.0.7 on 2025-11-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transparency",
            "0002_alter_ballotmeasure_options_alter_committee_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballotmeasure",
            name="measure_number",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
