# Generated by Django 5.0.7 on 2025-10-30 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0002_contribution_year_expenditure_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributions",
                to="transparency.iecommittee",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributions",
                to="transparency.donorentity",
            ),
        ),
    ]
