# Generated by Django 5.0.7 on 2025-10-21 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0002_expenditure_candidate_alter_candidate_race_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenditure",
            name="support_oppose",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="expenditure",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transparency.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="expenditure",
            name="ie_committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transparency.iecommittee",
            ),
        ),
        migrations.AlterField(
            model_name="expenditure",
            name="race",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transparency.race",
            ),
        ),
    ]
