# Generated by Django 5.0.7 on 2025-11-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0003_alter_ballotmeasure_measure_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cycle",
            name="begin_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="cycle",
            name="end_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
