# Generated by Django 5.0.7 on 2025-11-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0004_alter_cycle_begin_date_alter_cycle_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballotmeasure",
            name="official_title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
