# Generated by Django 5.0.7 on 2025-10-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0004_party_candidate_party"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatementOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("office", models.CharField(blank=True, max_length=255, null=True)),
                ("party", models.CharField(blank=True, max_length=100, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("date_filed", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, help_text="Raw JSON data from the source", null=True
                    ),
                ),
            ],
        ),
    ]
