# Generated by Django 5.0.7 on 2025-11-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0005_alter_ballotmeasure_official_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatestatementofinterest",
            name="phone",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name="candidatestatementofinterest",
            index=models.Index(fields=["phone"], name="idx_soi_phone"),
        ),
    ]
