# Generated by Django 5.0.7 on 2025-11-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0006_candidatestatementofinterest_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="phone",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
