# Generated by Django 5.0.7 on 2025-11-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0006_candidatestatementofinterest_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatestatementofinterest",
            name="contact_date",
        ),
        migrations.RemoveField(
            model_name="candidatestatementofinterest",
            name="pledge_date",
        ),
        migrations.AddField(
            model_name="candidatestatementofinterest",
            name="contacted_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date info packet was sent",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="candidatestatementofinterest",
            name="party",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="candidatestatementofinterest",
            name="pledge_received_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date pledge was received",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="candidatestatementofinterest",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="URL where SOI was scraped from"
            ),
        ),
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="contact_status",
            field=models.CharField(
                choices=[
                    ("uncontacted", "Uncontacted - Need to Send Email"),
                    ("contacted", "Contacted - Email Sent"),
                    ("no_email", "No Email Available"),
                    ("bounced", "Email Bounced"),
                ],
                db_index=True,
                default="uncontacted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="contacted_by",
            field=models.CharField(
                blank=True, help_text="Person who sent the email", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="candidatestatementofinterest",
            index=models.Index(fields=["email"], name="idx_soi_email"),
        ),
        migrations.AddIndex(
            model_name="candidatestatementofinterest",
            index=models.Index(fields=["party"], name="idx_soi_party"),
        ),
    ]
