# Generated by Django 5.0.7 on 2025-11-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0007_alter_candidatestatementofinterest_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatestatementofinterest",
            name="party",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
