# Generated by Django 5.0.7 on 2025-11-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0008_candidatestatementofinterest_party"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="contact_date",
            field=models.DateField(
                blank=True, db_column="contacted_date", db_index=True, null=True
            ),
        ),
    ]
