# Generated by Django 5.0.7 on 2025-11-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0009_alter_candidatestatementofinterest_contact_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatestatementofinterest",
            name="contact_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
