# Generated by Django 5.0.7 on 2025-11-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0010_alter_candidatestatementofinterest_contact_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatestatementofinterest",
            name="source_url",
            field=models.URLField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
