# Generated by Django 5.0.7 on 2025-11-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0002_add_email_tracking"),
        ("transparency", "0013_emailcampaign_emailtemplate_emaillog_and_more"),
    ]

    operations = []
