# Generated by Django 5.0.7 on 2025-11-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0014_merge_20251128_1025"),
    ]

    operations = []
