# Generated by Django 5.0.7 on 2025-12-20 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0017_transaction_dashboard_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdBuy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Screenshot/photo of the ad",
                        upload_to="ad_buys/%Y/%m/%d/",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL where ad appeared (if online)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "ad_date",
                    models.DateField(db_index=True, help_text="Date ad was observed"),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("tv", "Television"),
                            ("radio", "Radio"),
                            ("digital", "Digital/Online"),
                            ("print", "Print/Newspaper"),
                            ("mail", "Direct Mail"),
                            ("billboard", "Billboard/Outdoor"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                (
                    "paid_for_by",
                    models.CharField(
                        help_text="Committee/organization that paid for ad",
                        max_length=255,
                    ),
                ),
                (
                    "approximate_spend",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated cost (if known)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "how_known",
                    models.CharField(
                        choices=[
                            ("disclaimer", "Shown in disclaimer"),
                            ("research", "Found via research"),
                            ("estimate", "Estimated"),
                            ("unknown", "Unknown"),
                        ],
                        default="disclaimer",
                        max_length=50,
                    ),
                ),
                (
                    "support_oppose",
                    models.CharField(
                        choices=[
                            ("support", "Support"),
                            ("oppose", "Oppose"),
                            ("neutral", "Neutral/Informational"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "reported_by",
                    models.CharField(
                        help_text="Name/email of volunteer who reported this",
                        max_length=255,
                    ),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Has this been reviewed and approved by admin?",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("rejected", models.BooleanField(db_index=True, default=False)),
                ("rejection_reason", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ad Buy",
                "verbose_name_plural": "Ad Buys",
                "db_table": "ad_buys",
                "ordering": ["-ad_date", "-reported_at"],
            },
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("soi_initial", "Initial SOI Request"),
                    ("soi_followup", "SOI Follow-up"),
                    ("pledge_reminder", "Pledge Reminder"),
                    ("general", "General"),
                ],
                db_index=True,
                default="general",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="clicked_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="opened_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="sent_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("bounced", "Bounced"),
                ],
                db_index=True,
                default="sending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["tracking_id"], name="idx_emaillog_tracking"),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["status", "sent_at"], name="idx_emaillog_status_sent"
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["campaign", "status"], name="idx_emaillog_campaign_status"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["category", "is_active"], name="idx_template_cat_active"
            ),
        ),
        migrations.AddField(
            model_name="adbuy",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                help_text="Candidate this ad is about",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads_about_candidate",
                to="transparency.committee",
            ),
        ),
        migrations.AddField(
            model_name="adbuy",
            name="ie_committee",
            field=models.ForeignKey(
                blank=True,
                help_text="IE committee that paid for this ad",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ad_buys",
                to="transparency.committee",
            ),
        ),
        migrations.AddField(
            model_name="adbuy",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_ad_buys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="adbuy",
            index=models.Index(fields=["-ad_date"], name="idx_adbuy_date_desc"),
        ),
        migrations.AddIndex(
            model_name="adbuy",
            index=models.Index(
                fields=["verified", "-ad_date"], name="idx_adbuy_verified_date"
            ),
        ),
        migrations.AddIndex(
            model_name="adbuy",
            index=models.Index(
                fields=["candidate", "-ad_date"], name="idx_adbuy_candidate_date"
            ),
        ),
        migrations.AddIndex(
            model_name="adbuy",
            index=models.Index(
                fields=["ie_committee", "-ad_date"], name="idx_adbuy_ie_date"
            ),
        ),
        migrations.AddIndex(
            model_name="adbuy",
            index=models.Index(
                fields=["platform", "-ad_date"], name="idx_adbuy_platform_date"
            ),
        ),
        migrations.AddIndex(
            model_name="adbuy",
            index=models.Index(
                fields=["verified", "rejected"], name="idx_adbuy_status"
            ),
        ),
    ]
