# Generated by Django 5.0.7 on 2025-12-21 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0018_add_adbuy_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "totp_secret",
                    models.CharField(
                        blank=True,
                        help_text="TOTP secret for two-factor authentication",
                        max_length=32,
                    ),
                ),
                (
                    "is_2fa_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Has the user enabled 2FA?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_2fa_enabled"], name="idx_profile_user_2fa"
                    )
                ],
            },
        ),
    ]
