# Generated by Django 6.0.1 on 2026-01-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0019_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SOIScrapeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(db_index=True, max_length=36, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("candidates_found", models.IntegerField(default=0)),
                ("candidates_created", models.IntegerField(default=0)),
                ("candidates_updated", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("triggered_by", models.CharField(default="web", max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "soi_scrape_jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
