# Generated by Django 6.0.1 on 2026-01-15 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0020_soi_scrape_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="DarkMoneyDisclosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funding_source_name",
                    models.CharField(
                        help_text="Name of the entity that was the actual funding source",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount contributed by the funding source",
                        max_digits=14,
                    ),
                ),
                (
                    "election_year",
                    models.IntegerField(
                        db_index=True,
                        help_text="Year of the election this spending was for",
                    ),
                ),
                (
                    "target_candidates",
                    models.TextField(
                        blank=True,
                        help_text="Names of candidates targeted (comma-separated)",
                    ),
                ),
                (
                    "is_for_benefit",
                    models.BooleanField(
                        blank=True,
                        help_text="True if spending supported candidates, False if opposed",
                        null=True,
                    ),
                ),
                (
                    "disclosure_date",
                    models.DateField(
                        db_index=True,
                        help_text="Date the funding source was publicly revealed",
                    ),
                ),
                (
                    "disclosure_source",
                    models.TextField(
                        help_text="How the disclosure came about (lawsuit, investigation, etc.)"
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to news article or document about the disclosure",
                        max_length=500,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional context about this disclosure"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "funding_source_entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to Entity if they exist in our database",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dark_money_funded",
                        to="transparency.entity",
                    ),
                ),
                (
                    "ie_committee",
                    models.ForeignKey(
                        help_text="The IE committee that received/spent the dark money",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dark_money_disclosures",
                        to="transparency.committee",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        help_text="Office/race this spending was targeting",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transparency.office",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dark Money Disclosure",
                "verbose_name_plural": "Dark Money Disclosures",
                "db_table": "dark_money_disclosures",
                "ordering": ["-disclosure_date", "-amount"],
                "indexes": [
                    models.Index(fields=["election_year"], name="idx_darkmoney_year"),
                    models.Index(
                        fields=["ie_committee"], name="idx_darkmoney_committee"
                    ),
                    models.Index(
                        fields=["disclosure_date"], name="idx_darkmoney_disclosed"
                    ),
                    models.Index(
                        fields=["election_year", "office"], name="idx_darkmoney_race"
                    ),
                ],
            },
        ),
    ]
