# Generated by Django 6.0.1 on 2026-01-15 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparency', '0021_add_dark_money_disclosure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('total_visits', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('top_pages', models.JSONField(default=dict, help_text='{"path": count, ...}')),
                ('countries', models.JSONField(default=dict, help_text='{"country_code": count, ...}')),
                ('regions', models.JSONField(default=dict, help_text='{"region": count, ...}')),
                ('desktop_visits', models.IntegerField(default=0)),
                ('mobile_visits', models.IntegerField(default=0)),
                ('tablet_visits', models.IntegerField(default=0)),
                ('browsers', models.JSONField(default=dict, help_text='{"browser": count, ...}')),
                ('referrers', models.JSONField(default=dict, help_text='{"referrer": count, ...}')),
                ('avg_time_on_site', models.FloatField(blank=True, help_text='Average seconds per session', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Analytics',
                'verbose_name_plural': 'Daily Analytics',
                'db_table': 'daily_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('visitor_id', models.CharField(blank=True, db_index=True, help_text='Persistent visitor ID from cookie', max_length=64)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('browser', models.CharField(blank=True, db_index=True, max_length=50)),
                ('os', models.CharField(blank=True, db_index=True, max_length=50)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('time_on_page', models.IntegerField(blank=True, help_text='Seconds spent on page', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Visit',
                'verbose_name_plural': 'Site Visits',
                'db_table': 'site_visits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'path'], name='idx_visit_time_path'), models.Index(fields=['country_code'], name='idx_visit_country'), models.Index(fields=['device_type'], name='idx_visit_device'), models.Index(fields=['session_id'], name='idx_visit_session'), models.Index(fields=['-timestamp'], name='idx_visit_recent')],
            },
        ),
    ]
