# Generated by Django 6.0.1 on 2026-01-19 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparency", "0022_add_site_analytics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=500)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("page", "Page"),
                            ("candidate_profile", "Candidate Profile"),
                            ("committee_profile", "Committee Profile"),
                            ("ie_spending", "IE Spending"),
                            ("dark_money", "Dark Money"),
                            ("race_analysis", "Race Analysis"),
                            ("document", "Document/PDF"),
                        ],
                        default="page",
                        max_length=50,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("views", models.IntegerField(default=0)),
                ("unique_visitors", models.IntegerField(default=0)),
                ("avg_time_on_page", models.FloatField(default=0, help_text="Seconds")),
                (
                    "bounce_rate",
                    models.FloatField(default=0, help_text="Percentage 0-100"),
                ),
                (
                    "scroll_depth_avg",
                    models.FloatField(default=0, help_text="Percentage 0-100"),
                ),
                ("total_clicks", models.IntegerField(default=0)),
                ("shares", models.IntegerField(default=0)),
                ("downloads", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "content_performance",
                "ordering": ["-date", "-views"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "-date"], name="idx_content_type_date"
                    )
                ],
                "unique_together": {("path", "date")},
            },
        ),
        migrations.CreateModel(
            name="HourlyTrafficPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("hour", models.IntegerField()),
                ("visits", models.IntegerField(default=0)),
                ("unique_visitors", models.IntegerField(default=0)),
                ("page_views", models.IntegerField(default=0)),
                ("desktop", models.IntegerField(default=0)),
                ("mobile", models.IntegerField(default=0)),
                ("tablet", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "hourly_traffic",
                "ordering": ["-date", "-hour"],
                "unique_together": {("date", "hour")},
            },
        ),
        migrations.CreateModel(
            name="ReferrerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=255)),
                ("full_url", models.URLField(blank=True, max_length=1000)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("social", "Social Media"),
                            ("search", "Search Engine"),
                            ("news", "News Site"),
                            ("direct", "Direct"),
                            ("email", "Email"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        help_text="twitter, facebook, google, etc.",
                        max_length=50,
                    ),
                ),
                ("visit_count", models.IntegerField(default=0)),
                ("unique_visitors", models.IntegerField(default=0)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("avg_pages_per_session", models.FloatField(default=1.0)),
                ("avg_session_duration", models.FloatField(default=0)),
                (
                    "bounce_rate",
                    models.FloatField(default=0, help_text="Percentage 0-100"),
                ),
            ],
            options={
                "db_table": "referrer_stats",
                "ordering": ["-visit_count"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "-visit_count"],
                        name="idx_ref_type_count",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=500)),
                (
                    "normalized_query",
                    models.CharField(
                        db_index=True, help_text="Lowercase, trimmed", max_length=500
                    ),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("visitor_id", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("results_count", models.IntegerField(default=0)),
                ("had_results", models.BooleanField(default=True)),
                ("clicked_result", models.BooleanField(default=False)),
                (
                    "clicked_position",
                    models.IntegerField(
                        blank=True, help_text="Position of clicked result", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("general", "General Search"),
                            ("candidate", "Candidate Search"),
                            ("committee", "Committee Search"),
                            ("transaction", "Transaction Search"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "search_queries",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["normalized_query", "-timestamp"],
                        name="idx_search_query_time",
                    ),
                    models.Index(fields=["had_results"], name="idx_search_no_results"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "session_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("visitor_id", models.CharField(db_index=True, max_length=64)),
                ("started_at", models.DateTimeField(db_index=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("page_count", models.IntegerField(default=0)),
                (
                    "pages_visited",
                    models.JSONField(
                        default=list, help_text="Ordered list of pages visited"
                    ),
                ),
                ("entry_page", models.CharField(blank=True, max_length=500)),
                ("exit_page", models.CharField(blank=True, max_length=500)),
                (
                    "engagement_score",
                    models.CharField(
                        choices=[
                            ("casual", "Casual"),
                            ("interested", "Interested"),
                            ("engaged", "Engaged"),
                            ("power_user", "Power User"),
                        ],
                        default="casual",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_type", models.CharField(blank=True, max_length=20)),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("referrer", models.URLField(blank=True, max_length=1000)),
                (
                    "referrer_domain",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "utm_source",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
                ("is_bot", models.BooleanField(default=False)),
                (
                    "is_bounced",
                    models.BooleanField(default=False, help_text="Single page visit"),
                ),
            ],
            options={
                "db_table": "user_sessions",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["visitor_id"], name="idx_session_visitor"),
                    models.Index(fields=["started_at"], name="idx_session_started"),
                    models.Index(
                        fields=["engagement_score"], name="idx_session_engagement"
                    ),
                    models.Index(
                        fields=["referrer_domain"], name="idx_session_referrer"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnomalyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("traffic_spike", "Unusual Traffic Spike"),
                            ("traffic_drop", "Unusual Traffic Drop"),
                            ("bot_attack", "Potential Bot Attack"),
                            ("geo_anomaly", "Geographic Anomaly"),
                            ("error_spike", "Error Rate Spike"),
                            ("candidate_viral", "Candidate Going Viral"),
                            ("api_abuse", "API Abuse Detected"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("metric_name", models.CharField(blank=True, max_length=100)),
                ("expected_value", models.FloatField(blank=True, null=True)),
                ("actual_value", models.FloatField(blank=True, null=True)),
                ("threshold", models.FloatField(blank=True, null=True)),
                ("related_path", models.CharField(blank=True, max_length=500)),
                ("related_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("related_country", models.CharField(blank=True, max_length=100)),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "anomaly_alerts",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["alert_type", "-detected_at"],
                        name="idx_alert_type_time",
                    ),
                    models.Index(
                        fields=["severity", "is_acknowledged"],
                        name="idx_alert_severity",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="APIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(db_index=True, max_length=500)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "api_key",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("status_code", models.IntegerField(default=200)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("response_size_bytes", models.IntegerField(blank=True, null=True)),
                ("is_rate_limited", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_usage",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["endpoint", "-timestamp"], name="idx_api_endpoint_time"
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"], name="idx_api_ip_time"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CandidateView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_name", models.CharField(db_index=True, max_length=255)),
                ("office", models.CharField(blank=True, max_length=255)),
                (
                    "district",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("session_id", models.CharField(blank=True, max_length=64)),
                ("visitor_id", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("region", models.CharField(blank=True, db_index=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "time_on_page",
                    models.IntegerField(blank=True, help_text="Seconds", null=True),
                ),
                ("scrolled_to_bottom", models.BooleanField(default=False)),
                ("clicked_donation_link", models.BooleanField(default=False)),
                ("viewed_ie_spending", models.BooleanField(default=False)),
                ("referrer", models.URLField(blank=True, max_length=1000)),
                ("referrer_domain", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_views",
                        to="transparency.entity",
                    ),
                ),
            ],
            options={
                "db_table": "candidate_views",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["candidate_name", "-timestamp"],
                        name="idx_candview_name_time",
                    ),
                    models.Index(fields=["district"], name="idx_candview_district"),
                    models.Index(fields=["region"], name="idx_candview_region"),
                ],
            },
        ),
    ]
