# Generated by Django 6.0.1 on 2026-01-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparency', '0023_advanced_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='FECIndependentExpenditure',
            fields=[
                ('fec_file_id', models.CharField(help_text='FEC file ID (unique identifier for this expenditure)', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('transaction_id', models.CharField(db_index=True, help_text='FEC transaction ID', max_length=100)),
                ('committee_id', models.CharField(db_index=True, help_text='FEC committee ID (e.g., C00484642)', max_length=20)),
                ('committee_name', models.CharField(db_index=True, help_text='Name of the committee making the expenditure', max_length=255)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, help_text='Amount of the expenditure', max_digits=14)),
                ('is_support', models.BooleanField(db_index=True, help_text='True for support, False for oppose')),
                ('candidate_id', models.CharField(db_index=True, help_text='FEC candidate ID (e.g., S8FL00273)', max_length=20)),
                ('candidate_name', models.CharField(db_index=True, help_text='Full candidate name', max_length=255)),
                ('candidate_first_name', models.CharField(blank=True, help_text='Candidate first name', max_length=100)),
                ('candidate_last_name', models.CharField(db_index=True, help_text='Candidate last name', max_length=100)),
                ('candidate_party', models.CharField(db_index=True, help_text='Candidate party (e.g., REP, DEM)', max_length=10)),
                ('candidate_office', models.CharField(db_index=True, help_text='H for House, S for Senate', max_length=10)),
                ('candidate_office_district', models.CharField(blank=True, help_text='Congressional district (for House races)', max_length=10, null=True)),
                ('race', models.CharField(db_index=True, help_text='Race identifier (e.g., AZ-S1, AZ-06)', max_length=20)),
                ('cycle', models.IntegerField(db_index=True, help_text='Election year/cycle')),
                ('expenditure_date', models.DateField(blank=True, db_index=True, help_text='Date of the expenditure', null=True)),
                ('filing_date', models.DateField(blank=True, db_index=True, help_text='Date the expenditure was filed with FEC', null=True)),
                ('expenditure_description', models.TextField(blank=True, help_text='Description of the expenditure')),
                ('payee_name', models.CharField(blank=True, db_index=True, help_text='Name of payee receiving the expenditure', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FEC Independent Expenditure',
                'verbose_name_plural': 'FEC Independent Expenditures',
                'db_table': 'fec_independent_expenditures',
                'ordering': ['-expenditure_date', '-amount'],
                'indexes': [models.Index(fields=['committee_id', '-expenditure_date'], name='idx_fec_ie_comm_date'), models.Index(fields=['committee_name'], name='idx_fec_ie_comm_name'), models.Index(fields=['candidate_id', '-expenditure_date'], name='idx_fec_ie_cand_date'), models.Index(fields=['candidate_last_name'], name='idx_fec_ie_cand_name'), models.Index(fields=['race', 'cycle'], name='idx_fec_ie_race_cycle'), models.Index(fields=['cycle', 'is_support'], name='idx_fec_ie_cycle_support'), models.Index(fields=['-amount'], name='idx_fec_ie_amount_desc'), models.Index(fields=['candidate_party', 'cycle', '-amount'], name='idx_fec_ie_party_cycle'), models.Index(fields=['candidate_office', 'race', 'cycle'], name='idx_fec_ie_office_race')],
            },
        ),
    ]
